spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        tokens-in:
          destination: tokens
          contentType: application/json
        tokens-out:
          destination: tokens
          contentType: application/json
